// <auto-generated />
namespace PROCESA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class versao001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(versao001));
        
        string IMigrationMetadata.Id
        {
            get { return "202109130056550_versao001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
